[WIP] function calls
jamesrochabrun/SwiftAnthropic pull request #4
Opened 2024-03-28 16:34 UTC by cameron

We're having some issues with getting properly formatted JSON in our results, so figured I'd take a swing at this. 

It's incomplete, but I'd love early input — I don't have a lot of experience with Swift, so expect there are better ways. 

TODO:
- [ ] support more than just string,number,integer parameter types in tool definitions
- [ ] support more than just string parameters in invocations
- [ ] include API keys via xcconfig file

2024-03-28 18:40 UTC, bcherry commented on Sources/Anthropic/Public/Parameters/Message/MessageParameter.swift
> +        """
you can indent this all one more notch. the indentation within the string itself matches the closing `"""` not the opening one or the code block its contained in

2024-03-28 18:41 UTC, bcherry commented on Sources/Anthropic/Public/Parameters/Message/MessageParameter.swift
> +                \(parameters.map { $0.toXML() }.joined(separator:"\n\t\t"))
since this string is composed with spaces instead of tabs, its probably better to continue using spaces instead of tabs within the parameter list

2024-03-28 18:43 UTC, bcherry commented on Sources/Anthropic/Public/Parameters/Message/MessageParameter.swift
> +   // When non-empty, `stopSequences` will automatically include "</function_calls>", per Anthropic's API docs
link the docs

2024-03-28 18:43 UTC, bcherry commented on Sources/Anthropic/Public/Parameters/Message/MessageParameter.swift
> +"""
i'd link the doc this comes from so its clear its the expressly-suggested way to integrate this https://docs.anthropic.com/claude/docs/functions-external-tools

2024-04-05 06:59 UTC, jamesrochabrun commented
sorry the late response please check this new release https://github.com/jamesrochabrun/SwiftAnthropic/releases/tag/1.4

2024-04-06 19:47 UTC, jamesrochabrun commented
@cameron Thanks for your contribution! I think you can use now the beta version of function calling.

2024-04-10 05:44 UTC, jamesrochabrun requested changes
Thanks for the effort on this, lucky for us Anthropic released a cleaner function calling API, will follow up on supporting that path and also answering this issue asap https://github.com/jamesrochabrun/SwiftAnthropic/issues/7

2024-04-10 18:05 UTC, closed without merging